# Generated by Django 2.2.26 on 2023-06-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230623_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='x480',
            new_name='x2160',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
