# Generated by Django 2.2.26 on 2023-06-26 00:35

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movie_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='x1080',
            field=models.FileField(upload_to='torrents/%Y/%m/%d', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='x2160',
            field=models.FileField(upload_to='torrents/%Y/%m/%d', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='x720',
            field=models.FileField(upload_to='torrents/%Y/%m/%d', validators=[core.validators.validate_file_extension]),
        ),
    ]
