# Generated by Django 2.2.26 on 2023-06-26 20:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230626_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='x1080',
            field=models.FileField(blank=True, upload_to='torrents/%Y/%m/%d', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='x2160',
            field=models.FileField(blank=True, upload_to='torrents/%Y/%m/%d', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='x720',
            field=models.FileField(blank=True, upload_to='torrents/%Y/%m/%d', validators=[core.validators.validate_file_extension]),
        ),
    ]
