# Generated by Django 2.2.26 on 2023-06-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSuggestion',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('movie_titles', models.TextField(help_text='Enter movie title on a new line')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
