# Generated by Django 2.2.26 on 2023-06-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230626_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesuggestion',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
