# Generated by Django 2.2.26 on 2023-06-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_movie_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_tags',
            field=models.TextField(help_text='seprate tags with a comman(,)', max_length=300),
        ),
    ]
