# Generated by Django 2.2.26 on 2023-06-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230626_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='trailer_link',
            new_name='thriller_link',
        ),
    ]
