# Generated by Django 2.2.26 on 2023-06-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_movie_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
