# Generated by Django 2.2.26 on 2023-06-27 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230627_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='x1080',
            new_name='x_1080',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='x2160',
            new_name='x_2160',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='x720',
            new_name='x_720',
        ),
    ]
