# Generated by Django 4.2.2 on 2023-07-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='1/10', help_text='1/10', max_length=20),
        ),
    ]
