# Generated by Django 4.2.2 on 2023-07-08 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_views_count_movie_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
            preserve_default=False,
        ),
    ]
