# Generated by Django 4.2.2 on 2023-07-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateField(auto_created=True, default='2023-12-10'),
            preserve_default=False,
        ),
    ]
