# Generated by Django 4.2.2 on 2023-07-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_review_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='locked_movie_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='locked_x_1080_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='locked_x_2160_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='locked_x_720_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
