# Generated by Django 4.2.2 on 2023-07-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_movie_locked_movie_link_movie_locked_x_1080_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='locked_movie_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='locked_x_1080_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='locked_x_2160_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='locked_x_720_link',
            field=models.URLField(blank=True),
        ),
    ]
